### ISSUE TITLE
can't build successfully

### ISSUE THREAD

**Issue by neuliyiping** [lirios/power-manager#8]
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "LiriCMakeShared"
  (requested version 1.0.0) with any of the following names:

    LiriCMakeSharedConfig.cmake
    liricmakeshared-config.cmake

  Add the installation prefix of "LiriCMakeShared" to CMAKE_PREFIX_PATH or
  set "LiriCMakeShared_DIR" to a directory containing one of the above files.
  If "LiriCMakeShared" provides a separate development package or SDK, be
  sure it has been installed.

-- Configuring incomplete, errors occurred!

what can i do for this?

**Comment by plfiorini** [comment]
You need [this](https://github.com/lirios/cmake-shared.git) with other dependencies, all listed in README.md.
